env:
  IMAGE_REPO:   eosio/history-tools
  #
  # The following environment variables are exported by `hooks/pre-command`
  #   - IMAGE_BRANCH_TAG
  #   - GIT_SHORT_HASH
  #   - DOCKER_FILE_COMMIT_SHORT_HASH

steps:
  - label: ":gear::docker: Build docker image"
    command: "./.cicd/docker-build.sh"
    agents:
      queue: "automation-eks-eos-builder-fleet"

  - wait

  - label: "Run integration test against eos(develop)"
    timeout: ${TIMEOUT:-10}
    command: .cicd/helpers/execute_test.sh develop
    agents:
      queue: "automation-eks-eos-builder-fleet"

  - wait

  - label: "Run integration test against eos(release/2.1.x)"
    timeout: ${TIMEOUT:-10}
    command: .cicd/helpers/execute_test.sh release_2.1.x
    agents:
      queue: "automation-eks-eos-builder-fleet"
