steps:

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "docker build -f ./ubuntu-18.04.dockerfile ."
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-15}
    skip: $SKIP_UBUNTU_18

  - wait

  - label: "execute python script"
    command: "python2.7 .cicd/helpers/get_eos.py"
    agents:
      queue: "automation-eks-eos-builder-fleet"