steps:

  - wait

  - name: "Docker Compose Test %n"
    plugins:
      - docker-compose#v3.0.3:
          run: history-tools
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18
