steps:

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "docker build -t eosio/history-tools:$BUILDKITE_COMMIT -f ./ubuntu-18.04.dockerfile ."
      - "docker push eosio/history-tools:$BUILDKITE_COMMIT"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-15}
    skip: $SKIP_UBUNTU_18

  - wait

  - label: "run integration test"
    command:
      - "./.cicd/helpers/execute_test.sh"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-15}
    skip: $SKIP_UBUNTU_18
