steps:

  - wait
  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - .cicd/helpers/update_builder_base.sh
      - "docker build -t eosio/history-tools:$BUILDKITE_COMMIT -f ./ubuntu-18.04.dockerfile ."
      - "./.cicd/helpers/execute_test.sh develop"
      - "./.cicd/helpers/execute_test.sh release_2.1.x"
      - "docker push eosio/history-tools:$BUILDKITE_COMMIT"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-30}
